# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% if previous %}\
    {% if previous.commit_id and commit_id %}
        [{{ previous.commit_id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ previous.commit_id }})...\
            [{{ commit_id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit_id }})
    {% endif %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
          {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))\
          {% if commit.footers %}\
            {% for footer in commit.footers %}\
              {% if footer.token == "BREAKING CHANGE" %} — **Migration:** {{ footer.value }}{% endif %}\
            {% endfor %}\
          {% endif %}\
    {% endfor %}
{% endfor %}\n
"""

[remote.github]
owner = "allohamora"
repo = "release-test"

[git]
filter_unconventional = false
commit_parsers = [
    { message = "^\\w+(\\([^)]*\\))?!:", group = "<!-- 00 -->⚠️ Breaking Changes" },
    { message = "^feat", group = "<!-- 01 -->🚀 Features" },
    { message = "^fix", group = "<!-- 02 -->🐛 Bug Fixes" },
    { message = "^perf", group = "<!-- 03 -->⚡ Performance" },
    { message = "^refactor", group = "<!-- 04 -->🚜 Refactor" },
    { message = "^doc", group = "<!-- 05 -->📚 Documentation" },
    { message = "^style", group = "<!-- 06 -->🎨 Styling" },
    { message = "^test", group = "<!-- 07 -->🧪 Testing" },
    { message = "^revert", group = "<!-- 08 -->◀️ Revert" },
    { body = ".*security", group = "<!-- 09 -->🛡️ Security" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore|^ci", group = "<!-- 10 -->⚙️ Miscellaneous Tasks" },
    { message = ".*", group = "<!-- 11 -->💼 Other" },
]
